# Generated by Django 3.0 on 2019-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=13)),
                ('specialization', models.CharField(max_length=100)),
                ('schedule', models.DateTimeField(verbose_name='Practice Schedule')),
            ],
        ),
    ]
