# Generated by Django 3.0 on 2019-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_medicines_patient_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
