# Generated by Django 3.0 on 2019-12-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.CharField(default=None, max_length=1000, verbose_name='url for photo'),
        ),
    ]
