# Generated by Django 3.0 on 2019-12-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
